apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-webserver-deployment-${BRANCH}
spec:
  selector:
    matchLabels:
      app: cpp-webserver-${BRANCH}
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cpp-webserver-${BRANCH}
    spec:
      containers:
      - name: cpp-webserver-${BRANCH}
        # Note: image name is defined by the end user. tag is the branch name
        image: ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${BRANCH}-${SHORT_HASH}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: cpp-web-port
      imagePullSecrets:
      - name: aws-ecr-pass
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-webserver-service-${BRANCH}
spec:
  selector:
      app: cpp-webserver-${BRANCH}
  ports:
    - protocol: TCP
      port: 80
      targetPort: cpp-web-port
  # For simplicitly of opening an ssh tunnel to the service without having to check the chosen IP
  clusterIP: 10.43.1.1
